---
- import_playbook: ../common/verify.yml

- name: Verify
  hosts: collectd-test
  tasks:
    - name: "Make sure python.conf exists"
      stat:
        path: "{{ collectd_conf_output_dir }}/python.conf"
      register: python_conf
      failed_when: "{{ not python_conf.stat.exists }}"

    - name: "Get contents of python.conf"
      slurp:
        path: "{{ collectd_conf_output_dir }}/python.conf"
      register: python_conf

    - debug:
        var: python_conf.content | b64decode

    - name: "Check that the config imports sqlalchemy"
      assert:
        that:
          - '"Import \"sqlalchemy_collectd.server.plugin\"" in python_conf.content | b64decode'
        fail_msg: "SQLAlchemy is not imported by python config"

    - name: "Check that collectd_sqlalchemy is configured as expected"
      assert:
        that:
          - '"<Module \"sqlalchemy_collectd.server.plugin\">" in python_conf.content | b64decode'
          - '"listen \"localhost\" 25827" in python_conf.content | b64decode'
          - '"loglevel \"info\"" in python_conf.content | b64decode'
