---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../common/prepare.yml
    cleanup: ../common/cleanup.yml
  inventory:
    host_vars:
      collectd-test:
        collectd_conf_output_dir: "/etc/collectd.d/"
verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
