---
- import_playbook: ../common/verify.yml

- name: Verify
  hosts: collectd-test
  tasks:
    - name: "Get amqp conf"
      stat:
        path: "{{ collectd_conf_output_dir }}/amqp1.conf"
      register: amqp_conf
      failed_when: "{{ not amqp_conf.stat.exists }}"

    - name: "Check that default interval was unchanged"
      command:
        grep "Interval" {{ collectd_conf_output_dir }}/amqp1.conf
      register: interval
      changed_when: false
      failed_when:
        - "{{ ( interval.stdout | length != 0 ) or ( interval.stderr_lines | length != 0 ) }}"
