---
- name: Check if rsyslog exists
  shell: systemctl list-unit-files --type=service | grep -q rsyslog
  register: rsyslog_config
  failed_when: rsyslog_config.rc == 2
- name: Configure if we can
  when:
    - rsyslog_config is changed
    - rsyslog_config.rc == 0
  block:
    - name: Log healthchecks in dedicated file
      when:
        - tripleo_collectd_enable_sensubility|bool
      register: logconfig_add
      copy:
        dest: /etc/rsyslog.d/
        src: files/openstack-healthcheck.conf
    - name: Remove healthcheck log
      when:
        - not tripleo_collectd_enable_sensubility|bool
      register: logconfig_rm
      file:
        path: /etc/rsyslog.d/openstack-healthcheck.conf
        state: absent
    - name: Reload rsyslogd if needed
      when: logconfig_add is changed or logconfig_rm is changed
      service:
        name: rsyslog
        state: restarted
