---
- name: "Generate the collectd config files"
  include_role:
    name: collectd_config

- name: "Update include dir for configs"
  command: |
    sed -i 's#{{ collectd_conf_output_dir }}#/etc/collectd.d/#g' {{ collectd_conf_output_dir }}/../collectd.conf
