---
- name: "Generate the collectd config files"
  include_role:
    name: collectd_config

- name: "Update include dir for configs"
  lineinfile:
    path: "{{ collectd_conf_output_dir }}/../collectd.conf"
    regexp: "^(.*){{ collectd_conf_output_dir }}(.*)$"
    line: '\1/etc/collectd.d/\2'
    backrefs: yes
