---
- name: Check if rsyslog exists
  shell: systemctl list-unit-files --type=service | grep -q rsyslog
  register: rsyslog_config
  failed_when: rsyslog_config.rc == 2
- name: Configure if we can
  when:
    - rsyslog_config is changed
    - rsyslog_config.rc == 0
  block:
    - name: Log healthchecks in dedicated file
      when:
        - collectd_enable_sensubility|bool
      register: logconfig_add
      copy:
        dest: /etc/rsyslog.d/openstack-healthcheck.conf
        content: |
          if ($programname startswith 'podman' and ($msg contains 'container exec' or $msg contains 'healthy')) or ($programname startswith 'systemd' and $msg contains 'podman healthcheck run') then -/var/log/containers/collectd/healthchecks.stdout
          & stop
    - name: Remove healthcheck log
      when:
        - not collectd_enable_sensubility|bool
      register: logconfig_rm
      file:
        path: /etc/rsyslog.d/openstack-healthcheck.conf
        state: absent
    - name: Reload rsyslogd if needed
      when: logconfig_add is changed or logconfig_rm is changed
      service:
        name: rsyslog
        state: restarted
