---
- name: create persistent directories
  file:
    path: "{{ item.path }}"
    state: directory
    setype: "{{ item.setype }}"
    mode: "{{ item.mode }}"
  with_items:
    - {'path': /var/log/containers/collectd, 'setype': container_file_t, 'mode': '0750'}
