---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
provisioner:
  name: ansible
  log: true
lint: |
  ansible-lint **/*.yml

verifier:
  name: ansible

scenario:
  name: lint
  test_sequence:
    - lint
