---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
    docker_networks:
      - name: collectd
        ipam_config:
          - subnet: "192.168.42.0/24"
            gateway: "192.168.42.254"
    networks:
      - name: collectd
        ipv4_address: "192.168.42.1"
  - name: collectd-server
    image: docker.io/tripleomaster/centos-binary-collectd:current-tripleo-rdo
    privileged: true
    networks:
      - name: collectd
        ipv4_address: "192.168.42.2"

provisioner:
  name: ansible
  log: true
  playbooks:
    cleanup: ../common/cleanup.yml
  inventory:
    host_vars:
      collectd-test:
        collectd_conf_output_dir: "/etc/collectd.d/"
verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
