---
- name: "Prepare the hosts for testing"
  hosts:
    - collectd-test
    - collectd-server
  tasks:
    - name: "Create a directory for the log file"
      file:
        path: /var/log/collectd/
        state: directory
        mode: 0776
