---
# TODO: Reconsider this later, but it seems like a bad fit right now, since
# there are two hosts in the scenario, and this relies on there being one, and
# using podman
#- import_playbook: ../common/verify.yml
- name: "(Re)start collectd service"
  hosts:
    - collectd-test
    - collectd-server
  tasks:
    - name: "Kill running collectd process"
      command:
        pkill -e -c collectd
      ignore_errors: true

    - name: "Start collectd"
      command:
        /usr/sbin/collectd -C /etc/collectd.conf

- name: Verify collectd-test
  hosts: collectd-test
  tasks:
    - name: "Check that network.conf exists"
      stat:
        path: "{{ collectd_conf_output_dir }}/network.conf"
      register: network_conf
      failed_when: "{{ not network_conf.stat.exists }}"

    - name: "Check contents of network.conf"
      command:
        cat {{ collectd_conf_output_dir }}/network.conf
      register: conf
      changed_when: True

    - debug:
       var: conf.stdout

    - name: "Check that the Server is configured"
      command:
        grep "<Server .*>" {{ collectd_conf_output_dir }}/network.conf
      register: output
      changed_when: False
      failed_when: "{{ output.stdout | length == 0 }}"

    - debug:
        var: output.stdout


- name: Verify collectd-server
  hosts: collectd-server
  tasks:
    - name: Check for files in conf output dir
      find:
        paths: /etc/collectd.d
        patterns: '*.conf'
      register: output
      failed_when: output.files|length == 0

    - name: "Check for collectd.conf"
      find:
        paths: /etc/
        patterns: collectd.conf
      register: conf
      failed_when: conf.files|length != 1

    - name: "Check for metrics received by the collectd server"
      command:
        collectdctl -s /var/run/collectd-socket listval
      retries: 3
      delay: 5
      register: plugins
      until: plugins.rc == 0
      changed_when: False
      failed_when: ( plugins.stdout_lines|length == 0 ) or ( plugins.stderr | length > 0 )

    - name: "Make sure the metrics on collectd-server are from collectd-test"
      shell: |
        set -o pipefail
        collectdctl -s /var/run/collectd-socket listval | grep ^collectd-test/ | wc -l
      register: test_plugins
      changed_when: False
      failed_when: "{{ plugins.stdout_lines | length != test_plugins.stdout | int }}"
