---
- import_playbook: ../common/verify.yml

- name: Verify
  hosts: collectd-test
  tasks:
    - name: "Get amqp conf"
      stat:
        path: "{{ collectd_conf_output_dir }}/amqp1.conf"
      register: amqp_conf
      failed_when: "{{ not amqp_conf.stat.exists }}"
# TODO: There are more tests that can be done here, like check values in the conf file.
